import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "doc",
      id: "overview",
      label: "Models",
    },
    {
      type: "category",
      label: "Providers",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "providers" }],
    },
  ],
};

export default sidebars;
